nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-3.2.0.cjs

logFilters:
  # Suppress YN0060 (INCOMPATIBLE_PEER_DEPENDENCY) log messages for react-virtualized package
  # Related issue: https://github.com/bvaughn/react-virtualized/pull/1740
  - pattern: "* provides react* with version *, which doesn't satisfy what react-virtualized requests"
    level: 'discard'
